---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04

suites:
  - name: web-ssl
    data_bags_path: ~/chef/rtvipr-chef-metadata/data_bags
    roles_path: ~/chef/rtvipr-chef-metadata/roles
    environments_path: ~/chef/rtvipr-chef-metadata/environments
    nodes_path: ~/chef/rtvipr-chef-metadata/nodes
    run_list:
      - recipe[rtnginxssl]
    attributes: {}

  - name: gf-ssl
    data_bags_path: ~/chef/rtvipr-chef-metadata/data_bags
    roles_path: ~/chef/rtvipr-chef-metadata/roles
    environments_path: ~/chef/rtvipr-chef-metadata/environments
    nodes_path: ~/chef/rtvipr-chef-metadata/nodes
    run_list:
      - recipe[rtbase::update-cache-blocking]
      - recipe[rtapp::web-worker]
    attributes: {}

  - name: service-ssl
    data_bags_path: ~/chef/rtvipr-chef-metadata/data_bags
    roles_path: ~/chef/rtvipr-chef-metadata/roles
    environments_path: ~/chef/rtvipr-chef-metadata/environments
    nodes_path: ~/chef/rtvipr-chef-metadata/nodes
    run_list:
      - recipe[rtbase::update-cache-blocking]
      - recipe[rtapp::web-worker]
    attributes: {}

